spring.application.name=book-library-api
server.port=8081
spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Equivalent de "migrations" : crée les tables selon tes classes Java
spring.jpa.hibernate.ddl-auto=update
# Pour voir les requêtes SQL dans la console
spring.jpa.show-sql=true
# Accès à l'interface graphique de la base
spring.h2.console.enabled=true
server.error.white-label.enabled=false
